// This file is automatically generated. Do not edit it directly.
import type { Database } from './types';

// Re-exporta la instancia única de Supabase para mantener compatibilidad
export { supabase } from '@/lib/supabase';