// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqohrltzgvabamkbrtyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xb2hybHR6Z3ZhYmFta2JydHljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5ODUwMTYsImV4cCI6MjA2ODU2MTAxNn0.6MEZbzdxSqmCCm6myVC0hlV-zGHPjVW4Qx4wMO3uP74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});